# see https://symfony.com/doc/current/reference/configuration/framework.html
framework:
    secret: '%env(APP_SECRET)%'
    csrf_protection: true
    session:
        handler_id: ~
    http_method_override: false
    trusted_proxies: '%env(TRUSTED_PROXIES)%'
    trusted_hosts: 
    - '%env(TRUSTED_HOSTS)%'
    - "intense-springs-77079.herokuapp.com"
    # See https://caddyserver.com/docs/caddyfile/directives/reverse_proxy#headers
    trusted_headers: ['x-forwarded-for', 'x-forwarded-proto']

    #esi: true
    #fragments: true
    php_errors:
        log: true

when@test:
    framework:
        test: true
